services:
  - type: web
    name: trendotalk
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node migrate.js && echo "Migration completed successfully" && NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trendotalk-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
    autoDeploy: false

databases:
  - name: trendotalk-db
    plan: free
    databaseName: trendotalk
    user: trendotalk